# Generated by Django 3.0.4 on 2020-04-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_auto_20200420_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='gender',
            field=models.CharField(default='Male', max_length=250),
        ),
    ]
