# Generated by Django 3.0.4 on 2020-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0009_add_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='sale_price',
            field=models.CharField(max_length=200),
        ),
    ]
