# Generated by Django 3.0.4 on 2020-05-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0012_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='course_ids',
            new_name='product_ids',
        ),
    ]
